export const exampleReceipt =
    {
        receiptNumber: "893eb429-c1f6-40b1-aff1-76c1795df783",
        active: true,
        storeNumber: "1001(Web)",
        case: 1,
        date: "2024-02-22T18:49:41.129Z",
        total: 2110,
        subTotal: 2110,
        amountPaid: 8000,
        totalTax: 805.53,
        change: 5890,
        cart: [
            {
                id: 1,
                barcode: 2010361,
                name: "Süt",
                stock: 20,
                price: 20,
                tax: 1,
                campaign: "buy3pay2",
                isFavourite: true,
                image: "",
                categoryId: 1,
                subCategoryId: 1,
                quantity: 2,
                discountedPrice: 0
            },
            {
                id: 3,
                barcode: 2010363,
                name: "Elma",
                stock: 30,
                price: 3,
                tax: 1,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 1,
                subCategoryId: 3,
                quantity: 2,
                discountedPrice: 0
            },
            {
                id: 4,
                barcode: 2010364,
                name: "Çikolatalı Pasta",
                stock: 10,
                price: 12,
                tax: 1,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 1,
                subCategoryId: 4,
                quantity: 2,
                discountedPrice: 0
            },
            {
                id: 13,
                barcode: 2010373,
                name: "Monopoly",
                stock: 7,
                price: 30,
                tax: 2,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 5,
                subCategoryId: 13,
                quantity: 1,
                discountedPrice: 0
            },
            {
                id: 9,
                barcode: 2010369,
                name: "Mikrodalga Fırın",
                stock: 8,
                price: 300,
                tax: 15,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 3,
                subCategoryId: 9,
                quantity: 1,
                discountedPrice: 0
            },
            {
                id: 10,
                barcode: 2010370,
                name: "Erkek Gömlek",
                stock: 12,
                price: 50,
                tax: 5,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 4,
                subCategoryId: 10,
                quantity: 1,
                discountedPrice: 0
            },
            {
                id: 11,
                barcode: 2010371,
                name: "Kadın Elbise",
                stock: 18,
                price: 75,
                tax: 6,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 4,
                subCategoryId: 11,
                quantity: 1,
                discountedPrice: 0
            },
            {
                id: 12,
                barcode: 2010372,
                name: "Çocuk Ayakkabı",
                stock: 22,
                price: 40,
                tax: 4,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 4,
                subCategoryId: 12,
                quantity: 1,
                discountedPrice: 0
            },
            {
                id: 8,
                barcode: 2010368,
                name: "Laptop",
                stock: 5,
                price: 1500,
                tax: 50,
                campaign: "studentTaxFree",
                isFavourite: false,
                image: "",
                categoryId: 3,
                subCategoryId: 8,
                quantity: 1,
                discountedPrice: 0
            },
            {
                id: 7,
                barcode: 2010367,
                name: "Şampuan",
                stock: 25,
                price: 10,
                tax: 2,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 2,
                subCategoryId: 7,
                quantity: 1,
                discountedPrice: 0
            },
            {
                id: 6,
                barcode: 2010366,
                name: "Çamaşır Deterjanı",
                stock: 40,
                price: 8,
                tax: 3,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 2,
                subCategoryId: 6,
                quantity: 1,
                discountedPrice: 0
            },
            {
                id: 5,
                barcode: 2010365,
                name: "Kola",
                stock: 50,
                price: 2,
                tax: 2,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 1,
                subCategoryId: 5,
                quantity: 1,
                discountedPrice: 0
            },
            {
                id: 2,
                barcode: 2010362,
                name: "Tavuk Göğsü",
                stock: 15,
                price: 25,
                tax: 2,
                campaign: "-20%",
                isFavourite: false,
                image: "",
                categoryId: 1,
                subCategoryId: 2,
                quantity: 1,
                discountedPrice: 0
            }
        ],
        transactions: [
            {
                price: 8000,
                type: "cash"
            }
        ]
    }