export const data = {
    id: 1,
    subtotal: 3463,
    total: 3423,
    cart: [
        {
            id: 1,
            barcode: 2010361,
            name: "Süt",
            stock: 20,
            price: 20,
            tax: 1,
            campaign: "buy3pay2",
            isfavourites: true,
            image: "",
            categoryId: 1,
            subCategoryId: 1,
            quantity: 5,
            discountedPrice: "16.00"
        },
        {
            id: 2,
            barcode: 2010362,
            name: "Tavuk Göğsü",
            stock: 15,
            price: 25,
            tax: 2,
            campaign: "-20%",
            isfavourites: false,
            image: "",
            categoryId: 1,
            subCategoryId: 2,
            quantity: 4,
            discountedPrice: 20
        },
        {
            id: 8,
            barcode: 2010368,
            name: "Laptop",
            stock: 5,
            price: 1500,
            tax: 50,
            campaign: "studentTaxFree",
            isfavourites: false,
            image: "",
            categoryId: 3,
            subCategoryId: 8,
            quantity: 2,
            discountedPrice: 0
        },
        {
            id: 3,
            barcode: 2010363,
            name: "Elma",
            stock: 30,
            price: 3,
            tax: 1,
            campaign: "",
            isfavourites: false,
            image: "",
            categoryId: 1,
            subCategoryId: 3,
            quantity: 1,
            discountedPrice: 0
        },
        {
            id: 13,
            barcode: 2010373,
            name: "Monopoly",
            stock: 7,
            price: 30,
            tax: 2,
            campaign: "",
            isfavourites: false,
            image: "",
            categoryId: 5,
            subCategoryId: 13,
            quantity: 7,
            discountedPrice: 0
        },
        {
            id: 10,
            barcode: 2010370,
            name: "Erkek Gömlek",
            stock: 12,
            price: 50,
            tax: 5,
            campaign: "",
            isfavourites: false,
            image: "",
            categoryId: 4,
            subCategoryId: 10,
            quantity: 1,
            discountedPrice: 0
        }
    ]
}