export const data =
    {
        total: 4193.03,
        subTotal: 4768,
        cart: [
            {
                id: 1,
                barcode: 2010361,
                name: "Süt",
                stock: 20,
                price: 20,
                tax: 1,
                campaign: "buy3pay2",
                isFavourite: true,
                image: "",
                categoryId: 1,
                subCategoryId: 1,
                quantity: 7,
                discountedPrice: 14.29
            },
            {
                id: 2,
                barcode: 2010362,
                name: "Tavuk Göğsü",
                stock: 15,
                price: 25,
                tax: 2,
                campaign: "-20%",
                isFavourite: false,
                image: "",
                categoryId: 1,
                subCategoryId: 2,
                quantity: 7,
                discountedPrice: 20
            },
            {
                id: 3,
                barcode: 2010363,
                name: "Elma",
                stock: 30,
                price: 3,
                tax: 1,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 1,
                subCategoryId: 3,
                quantity: 1,
                discountedPrice: 0
            },
            {
                id: 4,
                barcode: 2010364,
                name: "Çikolatalı Pasta",
                stock: 10,
                price: 12,
                tax: 1,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 1,
                subCategoryId: 4,
                quantity: 1,
                discountedPrice: 0
            },
            {
                id: 8,
                barcode: 2010368,
                name: "Laptop",
                stock: 5,
                price: 1500,
                tax: 0,
                campaign: "studentTaxFree",
                isFavourite: false,
                image: "",
                categoryId: 3,
                subCategoryId: 8,
                quantity: 1,
                discountedPrice: 1000
            },
            {
                id: 7,
                barcode: 2010367,
                name: "Şampuan",
                stock: 25,
                price: 10,
                tax: 2,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 2,
                subCategoryId: 7,
                quantity: 1,
                discountedPrice: 0
            },
            {
                id: 6,
                barcode: 2010366,
                name: "Çamaşır Deterjanı",
                stock: 40,
                price: 8,
                tax: 3,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 2,
                subCategoryId: 6,
                quantity: 1,
                discountedPrice: 0
            },
            {
                id: 5,
                barcode: 2010365,
                name: "Kola",
                stock: 50,
                price: 2,
                tax: 2,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 1,
                subCategoryId: 5,
                quantity: 5,
                discountedPrice: 0
            },
            {
                id: 9,
                barcode: 2010369,
                name: "Mikrodalga Fırın",
                stock: 8,
                price: 300,
                tax: 15,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 3,
                subCategoryId: 9,
                quantity: 6,
                discountedPrice: 0
            },
            {
                id: 10,
                barcode: 2010370,
                name: "Erkek Gömlek",
                stock: 12,
                price: 50,
                tax: 5,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 4,
                subCategoryId: 10,
                quantity: 1,
                discountedPrice: 0
            },
            {
                id: 11,
                barcode: 2010371,
                name: "Kadın Elbise",
                stock: 18,
                price: 75,
                tax: 6,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 4,
                subCategoryId: 11,
                quantity: 6,
                discountedPrice: 0
            },
            {
                id: 12,
                barcode: 2010372,
                name: "Çocuk Ayakkabı",
                stock: 22,
                price: 40,
                tax: 4,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 4,
                subCategoryId: 12,
                quantity: 10,
                discountedPrice: 0
            },
            {
                id: 13,
                barcode: 2010373,
                name: "Monopoly",
                stock: 7,
                price: 30,
                tax: 2,
                campaign: "",
                isFavourite: false,
                image: "",
                categoryId: 5,
                subCategoryId: 13,
                quantity: 7,
                discountedPrice: 0
            }
        ]
    }